Almost all scenes work!
1: BigPicture:
missing image files
2: DoubleRainbow
✅
3: Eqs
✅
4: ManyLines
✅
5: ManyLines2
✅
6: PinkFloyd
✅
7: Plot
AttributeError: 'Plot' object has no attribute 'setup_axes'
8: Reflection
TypeError: Passing Mobject methods to Scene.play is no longer supported. Use Mobject.animate instead.
9: Reprise
✅ this one is helpful!
10: Snell
TypeError: Mobject.__init__() got an unexpected keyword argument 'start_angle'
11: SnellBreakDown
✅